//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOP.Core.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        public Booking()
        {
            this.Feedbacks = new HashSet<Feedback>();
        }
    
        public int Id { get; set; }
        public string VehicleOwnerName { get; set; }
        public Nullable<System.DateTime> VehicleOwnerDOB { get; set; }
        public string VehicleNumber { get; set; }
        public string VehicleLocation { get; set; }
        public string Address { get; set; }
        public decimal Mobile { get; set; }
        public string EmailId { get; set; }
        public int DelearId { get; set; }
        public System.DateTime DateOfService { get; set; }
        public int ServiceType { get; set; }
        public string DemandedRepairs { get; set; }
        public bool BookingOnBehalf { get; set; }
        public Nullable<int> ManufacturingYear { get; set; }
        public string City_Town { get; set; }
        public string VehicleModel { get; set; }
        public Nullable<int> SecretQuestion { get; set; }
        public string SecretAnswer { get; set; }
        public System.DateTime CreatedBy { get; set; }
        public Nullable<int> LastModifiedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
    
        public virtual Dealer Dealer { get; set; }
        public virtual SecretQuestion SecretQuestion1 { get; set; }
        public virtual ServiceType ServiceType1 { get; set; }
        public virtual ICollection<Feedback> Feedbacks { get; set; }
    }
}
