//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOP.Core.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dealer
    {
        public Dealer()
        {
            this.Bookings = new HashSet<Booking>();
            this.Feedbacks = new HashSet<Feedback>();
            this.Services = new HashSet<Service>();
            this.Workshops = new HashSet<Workshop>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string PrimaryContactPersonName { get; set; }
        public decimal PrimaryContactPersonNum { get; set; }
        public string SecondaryContactPersonName { get; set; }
        public Nullable<decimal> SecondaryContactPersonNum { get; set; }
        public Nullable<int> UserId { get; set; }
    
        public virtual ICollection<Booking> Bookings { get; set; }
        public virtual SopUser SopUser { get; set; }
        public virtual ICollection<Feedback> Feedbacks { get; set; }
        public virtual ICollection<Service> Services { get; set; }
        public virtual ICollection<Workshop> Workshops { get; set; }
    }
}
