//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOP.Core.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Feedback
    {
        public int Id { get; set; }
        public int CreatedBy { get; set; }
        public int BookingId { get; set; }
        public string Feedback1 { get; set; }
        public int DealerId { get; set; }
    
        public virtual Booking Booking { get; set; }
        public virtual Dealer Dealer { get; set; }
        public virtual SopUser SopUser { get; set; }
    }
}
