//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOP.Core.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentSummary
    {
        public int WorkshopId { get; set; }
        public int PackageId { get; set; }
        public int Amount { get; set; }
        public System.DateTime DateOfPayment { get; set; }
        public string Remarks { get; set; }
        public int Id { get; set; }
    
        public virtual SubscriptionPackage SubscriptionPackage { get; set; }
        public virtual Workshop Workshop { get; set; }
    }
}
