//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOP.Core.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SopUser
    {
        public SopUser()
        {
            this.Dealers = new HashSet<Dealer>();
            this.Feedbacks = new HashSet<Feedback>();
        }
    
        public int Id { get; set; }
        public string UserName { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public System.DateTime DOB { get; set; }
        public int Gender { get; set; }
        public string EmailId { get; set; }
        public decimal Mobile { get; set; }
        public string Password { get; set; }
        public int RoleId { get; set; }
        public int SecretQuestionId { get; set; }
        public string SecretAnswer { get; set; }
    
        public virtual ICollection<Dealer> Dealers { get; set; }
        public virtual ICollection<Feedback> Feedbacks { get; set; }
        public virtual Role Role { get; set; }
        public virtual SecretQuestion SecretQuestion { get; set; }
    }
}
